export const ONBOARDING_PROMPTS = [
  {
    id: "move_first_keypress",
    trigger: "first_move",
    text: "Move with WASD / left-stick",
    persistKey: "move_first_keypress",
  },
  {
    id: "look_first_mouse",
    trigger: "first_look",
    text: "Look around with the mouse / right-stick",
    persistKey: "look_first_mouse",
  },
  {
    id: "cast_first_fire",
    trigger: "first_cast",
    text: "Left-click / RT casts your spell",
    persistKey: "cast_first_fire",
  },
  {
    id: "block_first_incoming",
    trigger: "block_incoming",
    text: "Hold right-click / LT to block. Time it just before a hit for a perfect block.",
    persistKey: "block_first_incoming",
  },
  {
    id: "blink_first_low_hp",
    trigger: "blink_low_hp",
    text: "Blink (Shift/Q/B) to dash through danger.",
    persistKey: "blink_first_low_hp",
  },
  {
    id: "objective_first_active",
    trigger: "objective_active",
    text: "Objective active! Read the banner.",
    persistKey: "objective_first_active",
  },
  {
    id: "hazard_first_step",
    trigger: "hazard_step",
    text: "Rift surge — get out!",
    persistKey: "hazard_first_step",
  },
  {
    id: "boss_first_spawn",
    trigger: "boss_spawn",
    text: "Boss wave. Watch the health bar.",
    persistKey: "boss_first_spawn",
  },
  {
    id: "autocast_first_unlock",
    trigger: "autocast_unlock",
    text: "Auto-Cast unlocked. You can take a new spell next reward.",
    persistKey: "autocast_first_unlock",
  },
  {
    id: "perfect_block_first",
    trigger: "perfect_block",
    text: "Perfect block! Time your block just before a hit to reflect damage.",
    persistKey: "perfect_block_first",
  },
  {
    id: "blink_telegraph_first",
    trigger: "blink_telegraph",
    text: "Blink (Shift/Q/B) to dodge incoming attacks.",
    persistKey: "blink_telegraph_first",
  },
  {
    id: "autocast_hold_first",
    trigger: "autocast_hold",
    text: "Holding cast on an auto-fire spell will keep it firing.",
    persistKey: "autocast_hold_first",
  },
  {
    id: "wave_modifier_first",
    trigger: "wave_modifier",
    text: "This wave has a modifier — check the banner for effects.",
    persistKey: "wave_modifier_first",
  },
  {
    id: "objectives_first",
    trigger: "objectives",
    text: "Objective active! Complete it for bonus rewards.",
    persistKey: "objectives_first",
  },
  {
    id: "services_first",
    trigger: "services",
    text: "Services offer healing and tactical upgrades between waves.",
    persistKey: "services_first",
  },
  {
    id: "upgrade_tree_first",
    trigger: "upgrade_tree",
    text: "Upgrade tree — spend gold to unlock permanent spell upgrades.",
    persistKey: "upgrade_tree_first",
  },
  {
    id: "spell_switching_first",
    trigger: "spell_switching",
    text: "You can switch spells with number keys or mouse wheel.",
    persistKey: "spell_switching_first",
  },
];
