// text fields are i18n keys resolved via t() at display time in Onboarding.js
export const ONBOARDING_PROMPTS = [
  {
    id: "move_first_keypress",
    trigger: "first_move",
    text: "onboarding.move_first_keypress",
    persistKey: "move_first_keypress",
  },
  {
    id: "look_first_mouse",
    trigger: "first_look",
    text: "onboarding.look_first_mouse",
    persistKey: "look_first_mouse",
  },
  {
    id: "cast_first_fire",
    trigger: "first_cast",
    text: "onboarding.cast_first_fire",
    persistKey: "cast_first_fire",
  },
  {
    id: "block_first_incoming",
    trigger: "block_incoming",
    text: "onboarding.block_first_incoming",
    persistKey: "block_first_incoming",
  },
  {
    id: "blink_first_low_hp",
    trigger: "blink_low_hp",
    text: "onboarding.blink_first_low_hp",
    persistKey: "blink_first_low_hp",
  },
  {
    id: "objective_first_active",
    trigger: "objective_active",
    text: "onboarding.objective_first_active",
    persistKey: "objective_first_active",
  },
  {
    id: "hazard_first_step",
    trigger: "hazard_step",
    text: "onboarding.hazard_first_step",
    persistKey: "hazard_first_step",
  },
  {
    id: "boss_first_spawn",
    trigger: "boss_spawn",
    text: "onboarding.boss_first_spawn",
    persistKey: "boss_first_spawn",
  },
  {
    id: "autocast_first_unlock",
    trigger: "autocast_unlock",
    text: "onboarding.autocast_first_unlock",
    persistKey: "autocast_first_unlock",
  },
  {
    id: "perfect_block_first",
    trigger: "perfect_block",
    text: "onboarding.perfect_block_first",
    persistKey: "perfect_block_first",
  },
  {
    id: "blink_telegraph_first",
    trigger: "blink_telegraph",
    text: "onboarding.blink_telegraph_first",
    persistKey: "blink_telegraph_first",
  },
  {
    id: "autocast_hold_first",
    trigger: "autocast_hold",
    text: "onboarding.autocast_hold_first",
    persistKey: "autocast_hold_first",
  },
  {
    id: "wave_modifier_first",
    trigger: "wave_modifier",
    text: "onboarding.wave_modifier_first",
    persistKey: "wave_modifier_first",
  },
  {
    id: "objectives_first",
    trigger: "objectives",
    text: "onboarding.objectives_first",
    persistKey: "objectives_first",
  },
  {
    id: "services_first",
    trigger: "services",
    text: "onboarding.services_first",
    persistKey: "services_first",
  },
  {
    id: "upgrade_tree_first",
    trigger: "upgrade_tree",
    text: "onboarding.upgrade_tree_first",
    persistKey: "upgrade_tree_first",
  },
  {
    id: "spell_switching_first",
    trigger: "spell_switching",
    text: "onboarding.spell_switching_first",
    persistKey: "spell_switching_first",
  },
];
