// STATIC design data. Frozen — never mutated during a run. Buffs mutate a
// SpellInstance copy, never these objects.
export const SPELL_DEFINITIONS = Object.freeze({
  arcane_bolt: Object.freeze({
    id: "arcane_bolt",
    displayName: "Arcane Bolt",
    description: "Fast direct-damage bolt. Reliable, low cooldown.",
    castType: "projectile",
    damage: 22,
    cooldown: 0.42,
    projectileSpeed: 70,
    range: 80,
    color: 0x9a6cff,
    soundId: "arcane",
    starter: true,
  }),
  fireball: Object.freeze({
    id: "fireball",
    displayName: "Fireball",
    description: "Lobbed projectile that explodes for area damage on impact.",
    castType: "projectile_aoe",
    damage: 30,
    cooldown: 1.1,
    projectileSpeed: 42,
    range: 80,
    areaRadius: 6.5,
    color: 0xff7a33,
    soundId: "fire",
  }),
  frost_bolt: Object.freeze({
    id: "frost_bolt",
    displayName: "Frost Bolt",
    description: "Damages and chills the target, slowing its movement.",
    castType: "projectile",
    damage: 16,
    cooldown: 0.7,
    projectileSpeed: 60,
    range: 80,
    slowAmount: 0.5,
    slowDuration: 2.5,
    color: 0x5cc8ff,
    soundId: "frost",
  }),
  poison_bolt: Object.freeze({
    id: "poison_bolt",
    displayName: "Poison Bolt",
    description: "Light impact, then poisons the target for damage over time.",
    castType: "projectile_dot",
    damage: 8,
    cooldown: 0.85,
    projectileSpeed: 55,
    range: 80,
    dotDamage: 7,
    dotDuration: 4.0,
    dotTickRate: 0.5,
    color: 0x66dd55,
    soundId: "poison",
  }),
  chain_lightning: Object.freeze({
    id: "chain_lightning",
    displayName: "Chain Lightning",
    description: "Instantly strikes a target, arcing to nearby enemies.",
    castType: "hitscan_chain",
    damage: 18,
    cooldown: 1.3,
    range: 55,
    chainCount: 3,
    color: 0xa9e7ff,
    soundId: "chain",
  }),
  meteor: Object.freeze({
    id: "meteor",
    displayName: "Meteor",
    description: "Marks the ground you aim at, then crashes down for heavy AoE.",
    castType: "ground_aoe",
    damage: 55,
    cooldown: 2.6,
    range: 70,
    areaRadius: 8.5,
    color: 0xff5530,
    soundId: "meteor",
  }),
});

export const STARTER_SPELL_ID = "arcane_bolt";
export const UNLOCKABLE_SPELL_IDS = Object.keys(SPELL_DEFINITIONS).filter(
  (id) => !SPELL_DEFINITIONS[id].starter
);
